name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: windows-latest
    timeout-minutes: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: wally install

      - name: Build place file
        run: rojo build dev.project.json -o studio-tests.rbxlx

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: run-in-roblox --place studio-tests.rbxlx --script tests/init.server.lua
